"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get(k,f){try{return JSON.parse(localStorage.getItem(`bio_v2_${k}`))??f}catch{return f}},set(k,v){localStorage.setItem(`bio_v2_${k}`,JSON.stringify(v))}};
const state={route:"home",points:store.get("points",0),student:store.get("student",{name:"가입 전 학생"}),materialFilter:"all",assignmentFilter:"open",questionFilter:"all",loungeFilter:"all",currentMaterial:null,currentSlide:0,tool:"pen",drawing:false,history:[],formMode:null};
const materials=[];
let assignments=store.get("assignments",[]);
let questions=store.get("questions",[]);
let lounge=store.get("lounge",[]);
function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),2200)}
function updateUser(){const initial=state.student.name==='가입 전 학생'?'?':state.student.name.slice(-2,-1)||'?';$$('.avatar-button').forEach(x=>x.textContent=initial);$('.big-avatar').textContent=initial;$("#profileName").textContent=state.student.name;$("#headerPoints").textContent=state.points;$("#profilePoints").textContent=state.points}
function route(name){state.route=name;$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));$$('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===name));$('.main-nav').classList.remove('open');history.replaceState(null,"",`#${name}`);window.scrollTo({top:0,behavior:'smooth'});if(name==='materials')renderMaterials();if(name==='assignments')renderAssignments();if(name==='questions')renderQuestions();if(name==='lounge')renderLounge()}
$$('[data-route]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();route(b.dataset.route)}));$('#mobileMenu').onclick=()=>$('.main-nav').classList.toggle('open');
function savedMaterial(id){return !!store.get(`notes_${id}`,null)||!!store.get(`memo_${id}`,"")}
function renderMaterials(){const q=$('#materialSearch').value.trim();const list=materials.filter(m=>(state.materialFilter==='all'||(state.materialFilter==='saved'?savedMaterial(m.id):m.type===state.materialFilter))&&(!q||`${m.title} ${m.unit}`.includes(q)));$('#materialGrid').innerHTML=list.map(m=>`<article class="material-card"><div class="material-cover"><span class="tag ${m.color}">${m.type==='slide'?'수업 슬라이드':m.type==='link'?'수업 활동 링크':'학습지'}</span><b>${m.title}</b><small>${m.unit}</small></div><div class="material-info"><small>${m.date} · ${m.type==='link'?'외부 활동':m.pages+'쪽'}</small><h3>${m.title}</h3><p>${m.desc}</p><div><span class="saved-mark">${m.type==='link'?'게임·앱 새 탭에서 열기':savedMaterial(m.id)?'✓ 내 필기 저장됨':'필기하며 공부하기'}</span>${m.canDownload?`<button class="material-download" data-download-material="${m.id}">PDF 다운로드 ↓</button>`:''}<button data-open-material="${m.id}">${m.type==='link'?'활동 시작 ↗':'열기 →'}</button></div></div></article>`).join('')||'<div class="empty-panel page-empty"><span>▤</span><h3>등록된 수업 자료가 없습니다</h3><p>선생님이 슬라이드, 학습지 또는 활동 링크를 올리면 이곳에 표시됩니다.</p></div>';$$('[data-open-material]').forEach(b=>b.onclick=()=>openViewer(b.dataset.openMaterial));$$('[data-download-material]').forEach(b=>b.onclick=()=>window.bioDownloadMaterial?window.bioDownloadMaterial(b.dataset.downloadMaterial):toast('PDF 다운로드를 준비하지 못했습니다.'))}
$('#materialSearch').addEventListener('input',renderMaterials);$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.materialFilter=b.dataset.filter;renderMaterials()});
function renderAssignments(){const list=assignments.filter(a=>state.assignmentFilter==='done'?a.done:!a.done);$('#assignmentList').innerHTML=list.map(a=>`<article class="assignment-item ${a.done?'done':''}"><div class="assignment-date">${a.done?'<span>제출</span><strong>✓</strong>':`<span>D-${a.d}</span><strong>${a.d}</strong>`}</div><div><span class="tag ${a.done?'green':'coral'}">${a.done?'제출 완료':a.d<=2?'마감 임박':'진행 중'}</span><h3>${a.title}</h3><p>${a.desc}</p><small>${a.done?'제출한 파일을 다시 확인할 수 있어요.':a.due+' 마감'}</small></div><button data-submit-assignment="${a.id}">${a.done?'제출물 보기':'과제 제출'}</button></article>`).join('')||'<div class="empty-panel page-empty"><span>✓</span><h3>등록된 과제가 없습니다</h3><p>새 과제가 올라오면 이곳에서 확인할 수 있습니다.</p></div>';$$('[data-submit-assignment]').forEach(b=>b.onclick=()=>assignmentAction(b.dataset.submitAssignment));$('#openCount').textContent=assignments.filter(a=>!a.done).length;$('#doneCount').textContent=assignments.filter(a=>a.done).length}
$$('[data-assignment-filter]').forEach(b=>b.onclick=()=>{$$('[data-assignment-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.assignmentFilter=b.dataset.assignmentFilter;renderAssignments()});
function assignmentAction(id){const a=assignments.find(x=>String(x.id)===String(id));if(a.done){toast('제출 완료: '+a.title);return}openForm('assignment',{title:a.title,id:a.id})}
function imageGallery(urls=[]){return urls.length?`<div class="community-images">${urls.map(url=>`<a href="${url}" target="_blank" rel="noopener"><img src="${url}" alt="첨부 사진" loading="lazy"></a>`).join('')}</div>`:''}
function renderQuestions(){const list=questions.filter(q=>state.questionFilter==='all'||q.status===state.questionFilter||q.category===state.questionFilter);$('#questionList').innerHTML=list.map(q=>`<article class="question-row"><div><span class="tag ${q.status==='answered'?'blue':'green'}">${q.status==='answered'?'답변 있음':'답변 기다리는 중'}</span><span class="tag yellow">${q.subject}</span><h3>${q.title}</h3><p>${q.body}</p>${imageGallery(q.imageUrls)}<footer><span class="avatar ${q.author===state.student.name?'coral-bg':'mint'}">${q.author.slice(-2,-1)}</span><b>${q.author}</b><span>♡ ${q.likes}</span><span>답변 ${q.answers.length}</span></footer></div><div class="post-actions">${q.canEdit?`<button data-edit-question="${q.id}">수정</button>`:''}<button data-answer="${q.id}">답변 보기·추가</button></div></article>`).join('')||'<div class="empty-panel page-empty"><span>?</span><h3>해당 분류의 질문이 없습니다</h3><p>궁금한 점이 생기면 첫 질문을 올려 보세요.</p></div>';$$('[data-answer]').forEach(b=>b.onclick=()=>openQuestion(b.dataset.answer));$$('[data-edit-question]').forEach(b=>b.onclick=()=>window.bioEditQuestion?.(b.dataset.editQuestion))}
$$('[data-q-filter]').forEach(b=>b.onclick=()=>{$$('[data-q-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.questionFilter=b.dataset.qFilter;renderQuestions()});
function openQuestion(id){const q=questions.find(x=>String(x.id)===String(id));openForm('answer',{id:q.id,title:q.title,body:q.body,answers:q.answers})}
function renderLounge(){const list=lounge.filter(p=>state.loungeFilter==='all'||p.type===state.loungeFilter);$('#loungeGrid').innerHTML=list.map(p=>`<article class="lounge-card"><span class="tag ${p.type==='debate'?'coral':p.type==='article'?'blue':p.type==='activity'?'yellow':'green'}">${p.label}</span><h3>${p.title}</h3><p>${p.body}</p>${imageGallery(p.imageUrls)}<footer><b>${p.author}</b><span><button class="like-post" data-like-post="${p.id}" ${p.likedByMe||p.canLike===false?'disabled':''}>${p.likedByMe?'♥':'♡'} 좋아요 ${p.likes}</button> · 대화 ${p.comments}</span></footer>${p.canEdit?`<div class="post-actions"><button data-edit-lounge="${p.id}">수정</button></div>`:''}</article>`).join('')||'<div class="empty-panel page-empty"><span>♧</span><h3>아직 공유된 이야기가 없습니다</h3><p>흥미로운 생명과학 이야기를 처음으로 소개해 보세요.</p></div>';$$('[data-like-post]').forEach(b=>b.onclick=async()=>{if(window.bioLikeLounge){await window.bioLikeLounge(b.dataset.likePost);return}const p=lounge.find(x=>String(x.id)===b.dataset.likePost);p.likes++;p.likedByMe=true;store.set('lounge',lounge);renderLounge();toast('이 글에 공감했어요')});$$('[data-edit-lounge]').forEach(b=>b.onclick=()=>window.bioEditLounge?.(b.dataset.editLounge))}
$$('[data-lounge-filter]').forEach(b=>b.onclick=()=>{$$('[data-lounge-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.loungeFilter=b.dataset.loungeFilter;renderLounge()});
function openModal(id){$(id).classList.remove('hidden');document.body.style.overflow='hidden'}function closeModals(){ $$('.modal').forEach(m=>m.classList.add('hidden'));document.body.style.overflow=''}$$('[data-close]').forEach(b=>b.onclick=closeModals);$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModals()}));
$('#openJoin').onclick=()=>openModal('#joinModal');$('#openJoinFooter').onclick=()=>openModal('#joinModal');$('#joinForm').onsubmit=e=>{e.preventDefault();if($('#joinCode').value.trim().toUpperCase()!=='BIO2026'){ $('#joinError').textContent='인증번호를 다시 확인해 주세요.';return}state.student={name:$('#joinName').value.trim()};store.set('student',state.student);updateUser();closeModals();toast(`${state.student.name}님, 우리 반에 가입되었어요!`)};
$('#askQuestion').onclick=()=>openForm('question');$('#newLoungePost').onclick=()=>openForm('lounge');$('#assignmentHelp').onclick=()=>toast('과제 카드를 눌러 글이나 파일로 제출할 수 있어요.');
function openForm(mode,data={}){state.formMode={mode,data};const fields=$('#formFields');$('#formError').textContent='';if(mode==='question'){$('#formEyebrow').textContent='ASK A QUESTION';$('#formTitle').textContent='궁금한 점을 올려 보세요';$('#formSubmit').textContent='질문 등록하기';fields.innerHTML='<label>단원 분류<select name="category" required><option value="unit1">1단원</option><option value="unit2">2단원</option><option value="unit3">3단원</option></select></label><label>질문 제목<input name="title" required placeholder="무엇이 궁금한가요?"></label><label>자세한 내용<textarea name="body" required placeholder="어디까지 이해했고 무엇이 어려운지 적어 주세요."></textarea></label><label>사진 첨부 (선택, 최대 5장)<input name="images" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple></label>'}
 else if(mode==='lounge'){$('#formEyebrow').textContent='SHARE BIOLOGY';$('#formTitle').textContent='새로운 이야기를 나눠요';$('#formSubmit').textContent='라운지에 올리고 10P 받기';fields.innerHTML='<label>종류<select name="type"><option value="activity">내 활동 자랑</option><option value="article">기사·자료</option><option value="debate">토론</option><option value="wonder">신기한 생물</option></select></label><label>제목<input name="title" required placeholder="제목을 입력하세요"></label><label>내용<textarea name="body" required placeholder="공유할 내용을 적어 주세요."></textarea></label><label>사진 첨부 (선택, 최대 5장)<input name="images" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple></label><label>참고 링크 (선택)<input name="link" type="url" placeholder="https://"></label>'}
 else if(mode==='assignment'){$('#formEyebrow').textContent='SUBMIT ASSIGNMENT';$('#formTitle').textContent=data.title;$('#formSubmit').textContent='과제 제출하기';fields.innerHTML='<label>제출 내용<textarea name="body" placeholder="선생님께 전할 말이나 과제 내용을 적어 주세요."></textarea></label><label>파일 첨부<input name="file" type="file" accept=".pdf,.doc,.docx,.hwp,.hwpx,.ppt,.pptx,image/*"></label><small>파일 또는 글 중 하나 이상을 제출해 주세요.</small>'}
 else if(mode==='answer'){$('#formEyebrow').textContent='HELP A FRIEND';$('#formTitle').textContent=data.title;$('#formSubmit').textContent='답변 추가하기';fields.innerHTML=`<div class="question-context">${data.body}</div>${data.answers.map((a,i)=>`<div class="existing-answer"><b>${a.author}</b><p>${a.text}</p>${imageGallery(a.imageUrls)}<div class="answer-actions"><button type="button" data-helpful="${i}" data-helpful-answer="${a.id||''}" ${a.helpfulByMe||a.canMarkHelpful===false?'disabled':''}>${a.helpfulByMe?'♥ ':''}도움이 돼요 · ${a.helpful}</button>${a.canEdit?`<button type="button" data-edit-answer="${a.id}">수정</button>`:''}</div></div>`).join('')}<label>새 답변<textarea name="body" required placeholder="다른 답변이 있어도 자유롭게 설명을 추가할 수 있어요."></textarea></label><label>사진 첨부 (선택, 최대 5장)<input name="images" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple></label>`}
 openModal('#formModal');$$('[data-helpful]').forEach(b=>b.onclick=async()=>{if(window.bioHelpfulAnswer&&b.dataset.helpfulAnswer){await window.bioHelpfulAnswer(b.dataset.helpfulAnswer,data.id);return}const a=questions.find(q=>q.id===data.id).answers[+b.dataset.helpful];a.helpful++;a.helpfulByMe=true;store.set('questions',questions);b.textContent=`♥ 도움이 돼요 · ${a.helpful}`;b.disabled=true;toast('답변 작성자에게 도움이 됐다고 알렸어요!')});$$('[data-edit-answer]').forEach(b=>b.onclick=()=>{closeModals();window.bioEditAnswer?.(b.dataset.editAnswer)})}
$('#dynamicForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),{mode,data}=state.formMode;if(mode==='question'){const labels={unit1:'1단원',unit2:'2단원',unit3:'3단원'},category=fd.get('category');questions.unshift({id:Date.now(),title:fd.get('title'),body:fd.get('body'),author:state.student.name,status:'waiting',category,subject:labels[category],likes:0,answers:[]});store.set('questions',questions);closeModals();route('questions');toast('질문이 등록되었어요')}
 else if(mode==='lounge'){const labels={activity:'내 활동 자랑',article:'기사·자료',debate:'토론',wonder:'신기한 생물'};lounge.unshift({id:Date.now(),type:fd.get('type'),label:labels[fd.get('type')],title:fd.get('title'),body:fd.get('body'),author:state.student.name,likes:0,comments:0,link:fd.get('link')});state.points+=10;store.set('lounge',lounge);store.set('points',state.points);updateUser();closeModals();route('lounge');toast('라운지에 글을 올리고 10P를 받았어요!')}
 else if(mode==='assignment'){const body=fd.get('body').trim(),file=fd.get('file');if(!body&&(!file||!file.name)){ $('#formError').textContent='내용을 입력하거나 파일을 첨부해 주세요.';return}const a=assignments.find(x=>x.id===data.id);a.done=true;a.submission={body,file:file?.name||''};store.set('assignments',assignments);closeModals();renderAssignments();toast('과제가 안전하게 제출되었어요')}
 else if(mode==='answer'){const q=questions.find(x=>x.id===data.id);q.answers.push({author:state.student.name,text:fd.get('body'),helpful:0});q.status='answered';state.points+=10;store.set('questions',questions);store.set('points',state.points);updateUser();closeModals();renderQuestions();toast('친구에게 답변하고 10P를 받았어요!')}};

const slideTemplates=[
 {k:'01 · 생각 열기',h:'우리 몸의 온도는<br>왜 늘 비슷할까?',p:'더운 날에도, 추운 날에도 우리 몸은 약 36.5℃를 유지합니다.'},
 {k:'02 · 핵심 개념',h:'항상성과 음성 피드백',p:'몸의 상태가 정상 범위를 벗어나면 변화를 줄이는 방향으로 조절 작용이 일어납니다.'},
 {k:'03 · 조절 중추',h:'체온 조절의 중심,<br>시상 하부',p:'시상 하부는 혈액의 온도와 피부 온도 수용기의 정보를 함께 받아 반응을 결정합니다.',diagram:true},
 {k:'04 · 비교하기',h:'더울 때와 추울 때',p:'더울 때: 피부 혈관 확장, 땀 분비 증가<br>추울 때: 피부 혈관 수축, 몸 떨림 증가'},
 {k:'05 · 확인 질문',h:'배운 내용을 연결해 봅시다',p:'운동 뒤 땀이 나는 현상을 음성 피드백의 과정으로 설명해 보세요.',question:true}
];
let canvas,ctx,resizeObserver,activePointerId=null,activeLastPoint=null,activeHighlighterBase=null,activeHighlighterPath=null,activeStrokeChanged=false,viewerMode='pen';
function setViewerMode(mode){viewerMode=mode;const wrap=$('#lessonCanvas'),note=$('#noteCanvas');if(!wrap||!note)return;wrap.classList.toggle('scroll-mode',mode==='scroll');note.style.pointerEvents=mode==='scroll'?'none':'auto';note.style.touchAction=mode==='scroll'?'none':'none';$$('[data-view-mode]').forEach(b=>b.classList.toggle('active',b.dataset.viewMode===mode));if(mode==='scroll'){$('#slideContent').style.overflow='auto';wrap.scrollTop=0}else{$('#slideContent').style.overflow='hidden'}resizeCanvas()}
function openViewer(id){const m=materials.find(x=>x.id===id);if(!m)return;state.currentMaterial=m;state.currentSlide=0;state.history=[];$('#viewerTitle').textContent=m.title;$('#viewerType').textContent=m.type==='slide'?'수업 슬라이드':'학습지';$('#slideTotal').textContent=m.pages;$('#sideNote').value=store.get(`memo_${m.id}`,"");$('#slideThumbs').innerHTML=Array.from({length:m.pages},(_,i)=>`<div class="slide-thumb" data-slide="${i}"><b>${i+1}</b><br>${m.type==='worksheet'?'탐구 문제':'핵심 개념 '+(i+1)}</div>`).join('');openModal('#viewerModal');canvas=$('#noteCanvas');ctx=canvas.getContext('2d');setTimeout(()=>{resizeCanvas();renderSlide();loadDrawing()},0);resizeObserver?.disconnect();resizeObserver=new ResizeObserver(resizeCanvas);resizeObserver.observe($('#lessonCanvas'));$$('[data-slide]').forEach(t=>t.onclick=()=>goSlide(+t.dataset.slide))}
function renderSlide(){const m=state.currentMaterial,i=state.currentSlide,t=slideTemplates[i%slideTemplates.length];$('#slideCurrent').textContent=i+1;$$('.slide-thumb').forEach((x,n)=>x.classList.toggle('active',n===i));$('#prevSlide').disabled=i===0;$('#nextSlide').disabled=i===m.pages-1;const el=$('#slideContent');el.className=`slide-content ${m.type==='worksheet'?'worksheet':''}`;if(m.type==='worksheet')el.innerHTML=`<span class="slide-kicker">탐구 학습지 · ${i+1}</span><h3>${m.title}</h3><p><b>${i+1}.</b> 체온이 정상 범위를 벗어났을 때 우리 몸에서 일어나는 변화를 원인과 결과가 드러나도록 설명해 보세요.</p><div class="question-box">나의 생각을 필기 도구로 자유롭게 기록하세요.</div>`;else el.innerHTML=`<span class="slide-kicker">${t.k}</span><h3>${t.h}</h3><p>${t.p}</p>${t.diagram?'<div class="diagram"></div>':''}${t.question?'<div class="question-box">핵심어: 체온 · 시상 하부 · 땀샘 · 음성 피드백</div>':''}`}
function goSlide(i){saveDrawing();state.currentSlide=i;state.history=[];renderSlide();loadDrawing()}
function resizeCanvas(){if(!canvas)return;const rect=canvas.getBoundingClientRect(),ratio=devicePixelRatio||1,old=canvas.toDataURL();canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);if(old&&old!=='data:,'){const img=new Image;img.onload=()=>ctx.drawImage(img,0,0,rect.width,rect.height);img.src=old}}
function drawingKey(){return `drawing_${state.currentMaterial.id}_${state.currentSlide}`}
function loadDrawing(){const data=store.get(drawingKey(),null);ctx.clearRect(0,0,canvas.width,canvas.height);if(data){const img=new Image;img.onload=()=>ctx.drawImage(img,0,0,canvas.clientWidth,canvas.clientHeight);img.src=data}}
function saveDrawing(){if(!canvas||!state.currentMaterial)return;store.set(drawingKey(),canvas.toDataURL());store.set(`notes_${state.currentMaterial.id}`,true);$('#saveStatus').textContent='✓ 저장됨'}
function pointer(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function startDraw(e){if(activePointerId!==null||e.pointerType==='mouse'&&e.button!==0)return;if(state.tool==='text'){const p=pointer(e),txt=prompt('슬라이드에 넣을 메모를 입력하세요.');if(txt){snapshot();ctx.font='18px "Gowun Dodum"';ctx.fillStyle=$('#penColor').value;ctx.fillText(txt,p.x,p.y);saveSoon()}return}activePointerId=e.pointerId;activeStrokeChanged=false;state.drawing=true;try{canvas.setPointerCapture(e.pointerId)}catch{}activeLastPoint=pointer(e);if(state.tool==='highlighter'){activeHighlighterBase=document.createElement('canvas');activeHighlighterBase.width=canvas.width;activeHighlighterBase.height=canvas.height;activeHighlighterBase.getContext('2d').drawImage(canvas,0,0);activeHighlighterPath=new Path2D;activeHighlighterPath.moveTo(activeLastPoint.x,activeLastPoint.y)}e.preventDefault()}
function drawPointerPoint(e){const p=pointer(e),pressure=e.pointerType==='pen'?.65+Math.max(0,e.pressure)*.7:1;if(!activeLastPoint){activeLastPoint=p;return}if(!activeStrokeChanged){snapshot();activeStrokeChanged=true}ctx.lineCap='round';ctx.lineJoin='round';if(state.tool==='highlighter'&&activeHighlighterPath){activeHighlighterPath.lineTo(p.x,p.y);ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(activeHighlighterBase,0,0);ctx.restore();ctx.globalCompositeOperation='source-over';ctx.strokeStyle=$('#penColor').value;ctx.globalAlpha=.18;ctx.lineWidth=18*pressure;ctx.stroke(activeHighlighterPath)}else{ctx.beginPath();ctx.moveTo(activeLastPoint.x,activeLastPoint.y);ctx.lineTo(p.x,p.y);if(state.tool==='eraser'){ctx.globalCompositeOperation='destination-out';ctx.globalAlpha=1;ctx.lineWidth=22*pressure}else{ctx.globalCompositeOperation='source-over';ctx.strokeStyle=$('#penColor').value;ctx.globalAlpha=1;ctx.lineWidth=3*pressure}ctx.stroke()}activeLastPoint=p}
function moveDraw(e){if(!state.drawing||e.pointerId!==activePointerId)return;const points=e.getCoalescedEvents?.()||[e];points.forEach(drawPointerPoint);e.preventDefault()}
function endDraw(e){if(!state.drawing||e&&e.pointerId!==activePointerId)return;try{canvas.releasePointerCapture(activePointerId)}catch{}activePointerId=null;activeLastPoint=null;activeHighlighterBase=null;activeHighlighterPath=null;state.drawing=false;ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';if(activeStrokeChanged)saveSoon();activeStrokeChanged=false}
function snapshot(){state.history.push(canvas.toDataURL());if(state.history.length>20)state.history.shift()}function saveSoon(){$('#saveStatus').textContent='저장 중…';clearTimeout(saveSoon.t);saveSoon.t=setTimeout(saveDrawing,500)}
document.addEventListener('pointerdown',e=>{if(e.target?.id==='noteCanvas')startDraw(e)});document.addEventListener('pointermove',e=>{if(state.drawing)moveDraw(e)},{passive:false});document.addEventListener('pointerup',endDraw);document.addEventListener('pointercancel',endDraw);
$$('[data-tool]').forEach(b=>b.onclick=()=>{$$('[data-tool]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.tool=b.dataset.tool});$('#undoDrawing').onclick=()=>{const data=state.history.pop();if(!data){toast('되돌릴 최근 필기가 없습니다.');return}const img=new Image;img.onload=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.clientWidth,canvas.clientHeight);saveDrawing();toast('가장 최근 필기 한 번을 되돌렸습니다.')};img.src=data};$('#clearDrawing').onclick=()=>{if(confirm('이 페이지의 필기를 모두 지울까요?')){snapshot();ctx.clearRect(0,0,canvas.width,canvas.height);saveDrawing()}};$('#sideNote').addEventListener('input',()=>{if(!state.currentMaterial)return;store.set(`memo_${state.currentMaterial.id}`,$('#sideNote').value);$('#saveStatus').textContent='✓ 메모 저장됨'});$('#prevSlide').onclick=()=>goSlide(state.currentSlide-1);$('#nextSlide').onclick=()=>goSlide(state.currentSlide+1);$('#askFromMaterial').onclick=()=>{saveDrawing();const suggested=`${state.currentMaterial.title} ${state.currentSlide+1}쪽 질문`;closeModals();route('questions');openForm('question');$('[name=title]').value=suggested};$('#downloadNote').onclick=()=>{saveDrawing();const link=document.createElement('a');link.download=`${state.currentMaterial.title}-${state.currentSlide+1}쪽-필기.png`;link.href=canvas.toDataURL('image/png');link.click();toast('내 필기를 이미지로 저장했어요')};
document.addEventListener('click',e=>{const b=e.target.closest('[data-open-material]');if(b)openViewer(b.dataset.openMaterial)});window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModals()});
updateUser();renderMaterials();renderAssignments();renderQuestions();renderLounge();const initial=location.hash.slice(1);if(['home','materials','assignments','questions','lounge','profile'].includes(initial))route(initial);
(()=>{const css=document.createElement('style');css.textContent='.lesson-canvas.scroll-mode{aspect-ratio:auto;height:100%;min-height:720px}.lesson-canvas.scroll-mode .slide-content{overflow:auto}.lesson-canvas.scroll-mode #noteCanvas{cursor:default}';document.head.append(css);const tools=$('.viewer-tools');if(!tools||tools.querySelector('[data-view-mode]'))return;const pen=document.createElement('button'),scroll=document.createElement('button');pen.type=scroll.type='button';pen.dataset.viewMode='pen';scroll.dataset.viewMode='scroll';pen.textContent='필기';scroll.textContent='↕ 스크롤';tools.prepend(scroll);tools.prepend(pen);pen.onclick=()=>setViewerMode('pen');scroll.onclick=()=>setViewerMode('scroll')})();
document.addEventListener('click',e=>{const b=e.target.closest('[data-view-mode]');if(b){const wrap=$('#lessonCanvas');if(wrap)wrap.style.touchAction=b.dataset.viewMode==='scroll'?'pan-y':'none'}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-tool]');if(b&&viewerMode==='scroll'){const note=$('#noteCanvas');if(note)note.style.pointerEvents='auto';const wrap=$('#lessonCanvas');if(wrap)wrap.style.touchAction='pan-y'}});
document.querySelectorAll('[data-view-mode="pen"]').forEach(b=>b.remove());
