"use strict";
(()=>{
  const config=window.BIO_SUPABASE_CONFIG;
  if(!config||!window.supabase){console.error("Supabase client unavailable");return}
  const db=window.supabase.createClient(config.url,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});
  const AUTH_REDIRECT="https://cny2468-prog.github.io/biology-classroom/";
  const authSettingsPromise=fetch(`${config.url}/auth/v1/settings`,{headers:{apikey:config.publishableKey}}).then(response=>response.ok?response.json():({mailer_autoconfirm:true})).catch(()=>({mailer_autoconfirm:true}));
  const remote={session:null,user:null,profile:null,classes:[],selectedClass:null};
  const baseRenderMaterials=renderMaterials;
  renderMaterials=function(){baseRenderMaterials();document.querySelectorAll("#materialGrid [data-open-material]").forEach(button=>button.onclick=null);decorateTeacherMaterials()};
  window.bioBackend={db,remote};

  const authForm=document.querySelector("#joinForm");
  const joinCard=document.querySelector(".join-card");
  const authIntro=joinCard.querySelector("h2");
  authForm.innerHTML=`<div class="auth-tabs"><button type="button" class="active" data-auth-mode="signup">학생 가입</button><button type="button" data-auth-mode="teacher">교사 등록</button><button type="button" data-auth-mode="login">로그인</button></div><label data-register-only>이름<input name="displayName" placeholder="이름" required></label><label data-student-only>학번<input name="studentNumber" inputmode="numeric" pattern="[0-9]{5}" maxlength="5" placeholder="5자리 학번" required></label><label>정확한 이메일 주소<input name="email" type="email" autocomplete="email" placeholder="name@example.com" required></label><label>비밀번호<input name="password" type="password" minlength="8" autocomplete="current-password" placeholder="8자리 이상" required></label><label data-student-only data-optional>분반 인증번호 <small>(명단 학생은 생략 가능)</small><input name="classCode" placeholder="인증번호가 있으면 입력"></label><p class="form-error" id="joinError"></p><button class="primary wide" type="submit">가입하고 분반 들어가기</button><button class="resend-button hidden" id="forgotPassword" type="button">비밀번호를 잊었나요?</button><button class="resend-button hidden" id="resendConfirmation" type="button">가입 인증 메일 다시 받기</button>`;
  const authNote=joinCard.querySelector("small");
  authNote.textContent="실제로 메일을 받을 수 있는 주소를 입력해 주세요.";
  let authMode="signup";
  joinCard.querySelectorAll("[data-auth-mode]").forEach(button=>button.onclick=()=>{
    authMode=button.dataset.authMode;joinCard.querySelectorAll("[data-auth-mode]").forEach(x=>x.classList.toggle("active",x===button));
    joinCard.querySelectorAll("[data-register-only]").forEach(x=>x.classList.toggle("hidden",authMode==='login'));
    joinCard.querySelectorAll("[data-register-only] input").forEach(x=>x.required=authMode!=='login');
    joinCard.querySelectorAll("[data-student-only]").forEach(x=>x.classList.toggle("hidden",authMode!=='signup'));
    joinCard.querySelectorAll("[data-student-only] input").forEach(x=>x.required=authMode==='signup'&&!x.closest("[data-optional]"));
    document.querySelector("#resendConfirmation").classList.toggle("hidden",authMode!=='login');
    document.querySelector("#forgotPassword").classList.toggle("hidden",authMode!=='login');
    authIntro.textContent=authMode==='signup'?"우리 반에 들어오세요":authMode==='teacher'?"교사 계정을 등록하세요":"다시 만나 반가워요";
    authForm.querySelector("button[type=submit]").textContent=authMode==='signup'?"가입하고 분반 들어가기":authMode==='teacher'?"교사 계정 등록":"로그인";
    authNote.textContent=authMode==='signup'?"메일 인증을 마쳐야 가입이 완료됩니다.":authMode==='teacher'?"메일 인증 후 관리자에게 교사 권한을 요청하세요.":"가입할 때 인증한 이메일과 비밀번호를 입력해 주세요.";
  });
  authForm.onsubmit=async event=>{
    event.preventDefault();const fd=new FormData(authForm),errorBox=joinCard.querySelector("#joinError");errorBox.textContent="";
    const email=String(fd.get("email")).trim(),password=String(fd.get("password"));
    try{
      if(authMode!=='login'){
        const code=String(fd.get("classCode")||"").trim();if(authMode==='signup')sessionStorage.setItem("bio_pending_class_code",code);else sessionStorage.setItem("bio_pending_teacher_email",email);
        const requestedRole=authMode==='teacher'?"teacher":"student",studentNumber=String(fd.get("studentNumber")||"").trim();
        const displayName=String(fd.get("displayName")).trim(),authSettings=await authSettingsPromise,needsAppVerification=authSettings.mailer_autoconfirm===true;
        const {data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:AUTH_REDIRECT,data:{display_name:displayName,requested_role:requestedRole,student_number:authMode==='signup'?studentNumber:null,class_code:authMode==='signup'?code:null,email_verification_pending:needsAppVerification}}});if(error)throw error;
        if(needsAppVerification){const {error:mailError}=await db.auth.resetPasswordForEmail(email,{redirectTo:AUTH_REDIRECT});await db.auth.signOut();if(mailError)throw mailError;closeModals();toast("입력한 이메일로 가입 인증 링크를 보냈습니다. 링크에서 새 비밀번호를 설정해 주세요.");return}
        if(!data.session){closeModals();toast("가입 인증 메일을 보냈습니다. 메일의 링크를 눌러 가입을 완료해 주세요.");return}
        await activate(data.session);
      }else{const {data,error}=await db.auth.signInWithPassword({email,password});if(error)throw error;if(data.user?.user_metadata?.email_verification_pending){await db.auth.signOut();throw Error("이메일 인증이 아직 완료되지 않았습니다. 비밀번호 찾기에서 인증 메일을 다시 받아 주세요.")}await activate(data.session)}
      closeModals();toast("안전하게 로그인했습니다.");
    }catch(error){errorBox.textContent=koreanError(error.message)}
  };
  document.querySelector("#resendConfirmation").onclick=async()=>{const email=String(authForm.querySelector('[name="email"]').value).trim(),errorBox=joinCard.querySelector("#joinError");if(!email){errorBox.textContent="이메일을 먼저 입력해 주세요.";return}const settings=await authSettingsPromise,result=settings.mailer_autoconfirm===true?await db.auth.resetPasswordForEmail(email,{redirectTo:AUTH_REDIRECT}):await db.auth.resend({type:"signup",email,options:{emailRedirectTo:AUTH_REDIRECT}});if(result.error){errorBox.textContent=koreanError(result.error.message);return}errorBox.textContent="";toast("가입 인증 메일을 다시 보냈습니다. 스팸함도 확인해 주세요.")};
  document.querySelector("#forgotPassword").onclick=()=>{ensureAccountModals();closeModals();openModal("#passwordRequestModal")};
  function koreanError(message){if(/Email not confirmed/i.test(message))return"기존에 만든 계정의 이메일 인증이 필요합니다. 아래 인증 메일 다시 받기를 이용해 주세요.";if(/Invalid login/i.test(message))return"이메일 또는 비밀번호를 확인해 주세요.";if(/already registered/i.test(message))return"이미 가입된 이메일입니다. 로그인해 주세요.";if(/rate limit/i.test(message))return"잠시 후 다시 시도해 주세요.";return message}
  function ensureAccountModals(){
    if(document.querySelector("#passwordRequestModal"))return;
    document.body.insertAdjacentHTML("beforeend",`<div class="modal hidden account-modal" id="passwordRequestModal"><form class="modal-card form-card"><button class="modal-close" type="button">×</button><h2>비밀번호 찾기</h2><p>가입할 때 작성한 이름과 이메일을 입력하세요. 해당 이메일로 본인 인증 링크를 보냅니다.</p><label>이름<input name="displayName" required autocomplete="name"></label><label>가입 이메일<input name="email" type="email" required autocomplete="email"></label><p class="form-error"></p><button class="primary wide" type="submit">인증 메일 받기</button></form></div><div class="modal hidden account-modal" id="passwordRecoveryModal"><form class="modal-card form-card"><button class="modal-close" type="button">×</button><h2>새 비밀번호 설정</h2><p>등록한 이름을 한 번 더 확인한 뒤 새 비밀번호를 저장합니다.</p><label>가입할 때 작성한 이름<input name="displayName" required autocomplete="name"></label><label>새 비밀번호<input name="password" type="password" required minlength="8" autocomplete="new-password" placeholder="8자리 이상"></label><label>새 비밀번호 확인<input name="passwordConfirm" type="password" required minlength="8" autocomplete="new-password"></label><p class="form-error"></p><button class="primary wide" type="submit">새 비밀번호 저장</button></form></div>`);
    document.querySelectorAll(".account-modal .modal-close").forEach(button=>button.onclick=closeModals);
    document.querySelector("#passwordRequestModal form").onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,errorBox=form.querySelector(".form-error"),fd=new FormData(form),name=String(fd.get("displayName")).trim(),email=String(fd.get("email")).trim();errorBox.textContent="";try{sessionStorage.setItem("bio_password_reset_name",name);const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:AUTH_REDIRECT});if(error)throw error;closeModals();toast("입력한 이메일로 비밀번호 재설정 링크를 보냈습니다.")}catch(error){errorBox.textContent=koreanError(error.message)}};
    document.querySelector("#passwordRecoveryModal form").onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,errorBox=form.querySelector(".form-error"),fd=new FormData(form),name=String(fd.get("displayName")).trim(),password=String(fd.get("password")),confirmation=String(fd.get("passwordConfirm"));errorBox.textContent="";try{if(password!==confirmation)throw Error("새 비밀번호가 서로 일치하지 않습니다.");const {data:{user},error:userError}=await db.auth.getUser();if(userError||!user)throw userError||Error("인증 링크가 만료되었습니다. 비밀번호 찾기를 다시 진행해 주세요.");const {data:profile,error:profileError}=await db.from("profiles").select("display_name").eq("id",user.id).single();if(profileError)throw profileError;if(normalizeName(profile.display_name)!==normalizeName(name))throw Error("가입할 때 작성한 이름과 일치하지 않습니다.");const {error}=await db.auth.updateUser({password,data:{...user.user_metadata,email_verification_pending:false}});if(error)throw error;sessionStorage.removeItem("bio_password_reset_name");closeModals();toast("이메일 인증과 새 비밀번호 설정을 완료했습니다.");const {data:{session}}=await db.auth.getSession();if(session)await activate(session)}catch(error){errorBox.textContent=koreanError(error.message)}};
  }
  function normalizeName(value){return String(value||"").normalize("NFC").trim().replace(/\s+/g," ")}
  function openPasswordRecovery(){ensureAccountModals();const input=document.querySelector('#passwordRecoveryModal [name="displayName"]');input.value=sessionStorage.getItem("bio_password_reset_name")||"";closeModals();openModal("#passwordRecoveryModal")}

  async function activate(session){
    remote.session=session;remote.user=session.user;
    if(remote.user.user_metadata?.email_verification_pending){ensureAccountModals();return}
    const {data:profile,error}=await db.from("profiles").select("*").eq("id",remote.user.id).single();if(error)throw error;
    remote.profile=profile;state.student={name:profile.display_name};state.points=profile.points;updateUser();document.body.dataset.role=profile.role;
    installUserControls();installAccountSettings();if(profile.role==='teacher')installTeacherDirectory();await loadClasses();await loadRemoteContent();await syncPointsAndCelebrate();
  }
  async function syncPointsAndCelebrate(){
    if(!remote.user||remote.profile?.role!=='student')return;
    const {data:profile,error}=await db.from('profiles').select('points').eq('id',remote.user.id).single();if(error){console.error(error);return}
    remote.profile.points=profile.points;state.points=profile.points;updateUser();
    const {data:milestone,error:milestoneError}=await db.rpc('claim_point_500_milestone');if(milestoneError){console.error(milestoneError);return}
    if(milestone!==null)alert('축하합니다. 포인트 500점을 달성했습니다! 선생님께 가서 상품을 받으세요!');
  }
  function installUserControls(){
    let role=document.querySelector("#roleBadge");if(!role){role=document.createElement("span");role.id="roleBadge";document.querySelector(".user-area").prepend(role)}
    const awaitingTeacher=remote.profile.role!=="teacher"&&remote.user.user_metadata?.requested_role==="teacher";
    role.className=`role-badge ${awaitingTeacher?'teacher':remote.profile.role}`;role.textContent=remote.profile.role==='teacher'?"교사":awaitingTeacher?"교사 승인 대기":"학생";
    let out=document.querySelector("#logoutButton");if(!out){out=document.createElement("button");out.id="logoutButton";out.className="logout-button";out.textContent="로그아웃";document.querySelector(".user-area").append(out)}
    out.onclick=async()=>{await db.auth.signOut();location.reload()};
  }
  function installAccountSettings(){
    const host=document.querySelector(".activity-card");if(!host||host.querySelector("#accountSettings"))return;
    host.insertAdjacentHTML("beforeend",`<section class="account-settings" id="accountSettings"><h3>개인정보 수정</h3><form><label>이름<input name="displayName" required maxlength="40" value="${escapeHtml(remote.profile.display_name)}"></label><label>인증된 이메일<input value="${escapeHtml(remote.user.email||"")}" disabled></label><label>새 비밀번호 <small>(변경할 때만 입력)</small><input name="password" type="password" minlength="8" autocomplete="new-password" placeholder="8자리 이상"></label><label>새 비밀번호 확인<input name="passwordConfirm" type="password" minlength="8" autocomplete="new-password"></label><p class="form-error"></p><button class="primary" type="submit">개인정보 저장</button></form></section>`);
    host.querySelector("form").onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,fd=new FormData(form),errorBox=form.querySelector(".form-error"),displayName=String(fd.get("displayName")).trim(),password=String(fd.get("password")||""),confirmation=String(fd.get("passwordConfirm")||"");errorBox.textContent="";try{if(password&&password!==confirmation)throw Error("새 비밀번호가 서로 일치하지 않습니다.");const {error:profileError}=await db.from("profiles").update({display_name:displayName}).eq("id",remote.user.id);if(profileError)throw profileError;const changes={data:{display_name:displayName}};if(password)changes.password=password;const {data,error}=await db.auth.updateUser(changes);if(error)throw error;remote.user=data.user;remote.profile.display_name=displayName;state.student.name=displayName;updateUser();form.querySelector('[name="password"]').value="";form.querySelector('[name="passwordConfirm"]').value="";toast(password?"이름과 비밀번호를 변경했습니다.":"이름을 변경했습니다.")}catch(error){errorBox.textContent=koreanError(error.message)}};
  }
  let teacherStudents=[],teacherClassFilter="all";
  function installTeacherDirectory(){
    if(!document.querySelector("#teacherAdminNav")){const button=document.createElement("button");button.id="teacherAdminNav";button.dataset.route="teacherAdmin";button.textContent="학생 관리";button.onclick=()=>route("teacherAdmin");document.querySelector(".main-nav").append(button)}
    if(!document.querySelector('[data-page="teacherAdmin"]')){const section=document.createElement("section");section.className="page subpage";section.dataset.page="teacherAdmin";section.innerHTML='<div class="wrap page-head"><div><p class="eyebrow">STUDENT MANAGEMENT</p><h1>분반별 학생 관리</h1><p>가입한 학생만 엑셀의 세포 이동수업 분반에 따라 표시합니다.</p></div><div class="search-box">⌕ <input id="studentDirectorySearch" placeholder="학번 또는 이름 검색"></div></div><div class="wrap teacher-directory-summary"><b id="teacherStudentCount">0</b>명 표시 <span id="teacherStudentTotal"></span></div><div class="wrap teacher-class-filters" id="teacherClassFilters"></div><div class="wrap teacher-student-list" id="teacherStudentList"></div>';document.querySelector("main").append(section);section.querySelector("#studentDirectorySearch").addEventListener("input",renderTeacherDirectory)}
  }
  async function loadTeacherDirectory(){
    const [{data:people,error:peopleError},{data:enrollments,error:enrollmentError},{data:roster,error:rosterError}]=await Promise.all([db.from("profiles").select("id,display_name,points,created_at").eq("role","student").order("created_at",{ascending:false}),db.from("enrollments").select("student_id,class_id"),db.from("student_roster").select("student_number,display_name,claimed_by,class_id").order("student_number")]);if(peopleError)throw peopleError;if(rosterError)throw rosterError;if(enrollmentError)console.warn(enrollmentError);
    const classNameById=new Map(remote.classes.map(classroom=>[classroom.id,classroom.name])),classesByStudent=new Map();
    for(const row of enrollments||[]){const className=classNameById.get(row.class_id);if(!className)continue;const names=classesByStudent.get(row.student_id)||[];names.push(className);classesByStudent.set(row.student_id,names)}
    const rosterByClaimedId=new Map((roster||[]).filter(row=>row.claimed_by).map(row=>[row.claimed_by,row])),normalizeRosterName=value=>String(value||"").replace(/^\d{5}\s*/,"").replace(/\s+/g,"");
    teacherStudents=(people||[]).map(person=>{const enrolledClassIds=(enrollments||[]).filter(row=>row.student_id===person.id).map(row=>row.class_id),nameCandidates=(roster||[]).filter(row=>enrolledClassIds.includes(row.class_id)&&normalizeRosterName(row.display_name)===normalizeRosterName(person.display_name)),rosterRow=rosterByClaimedId.get(person.id)||(nameCandidates.length===1?nameCandidates[0]:null),rosterClass=rosterRow&&classNameById.get(rosterRow.class_id);return{...person,studentNumber:rosterRow?.student_number||"",numberCandidates:nameCandidates.map(row=>row.student_number),registered:true,classNames:rosterClass?[rosterClass]:classesByStudent.get(person.id)||[]}});renderTeacherDirectory();
  }
  function renderTeacherDirectory(){
    const host=document.querySelector("#teacherStudentList");if(!host)return;
    const q=document.querySelector("#studentDirectorySearch")?.value.trim()||"",compareKorean=(a,b)=>String(a).localeCompare(String(b),"ko",{sensitivity:"base",numeric:true});
    const classNames=[...new Set(teacherStudents.flatMap(student=>student.classNames))].sort(compareKorean),hasUnassigned=teacherStudents.some(student=>!student.classNames.length),availableFilters=["all",...classNames,...(hasUnassigned?["분반 미등록"]:[])];
    if(!availableFilters.includes(teacherClassFilter))teacherClassFilter="all";
    const filterHost=document.querySelector("#teacherClassFilters");
    filterHost.innerHTML=availableFilters.map(className=>`<button type="button" class="${teacherClassFilter===className?'active':''}" data-teacher-class="${escapeHtml(className)}">${className==="all"?"전체":escapeHtml(className)}</button>`).join("");
    filterHost.querySelectorAll("[data-teacher-class]").forEach(button=>button.onclick=()=>{teacherClassFilter=button.dataset.teacherClass;renderTeacherDirectory()});
    const matchesClass=student=>teacherClassFilter==="all"||(teacherClassFilter==="분반 미등록"?!student.classNames.length:student.classNames.includes(teacherClassFilter));
    const list=teacherStudents.filter(student=>matchesClass(student)&&(!q||student.display_name.includes(q)||student.studentNumber.includes(q))).sort((a,b)=>compareKorean(a.display_name,b.display_name)||String(a.studentNumber).localeCompare(String(b.studentNumber)));
    const numberedCount=teacherStudents.filter(student=>student.studentNumber).length;
    document.querySelector("#teacherStudentCount").textContent=list.length;document.querySelector("#teacherStudentTotal").textContent=`전체 가입 ${teacherStudents.length}명 · 학번 확인 ${numberedCount}명`;
    const groups=new Map();
    for(const student of list){const studentClasses=teacherClassFilter!=="all"?[teacherClassFilter]:student.classNames.length?[...new Set(student.classNames)].sort(compareKorean):["분반 미등록"];for(const className of studentClasses){if(!groups.has(className))groups.set(className,[]);groups.get(className).push(student)}}
    const orderedGroups=[...groups.entries()].sort(([a],[b])=>a==="분반 미등록"?1:b==="분반 미등록"?-1:compareKorean(a,b));
    const classOptions=[...remote.classes].sort((a,b)=>compareKorean(a.name,b.name)).map(classroom=>`<option value="${classroom.id}">${escapeHtml(classroom.name)}</option>`).join("");
    host.innerHTML=orderedGroups.map(([className,students])=>`<section class="teacher-class-group"><header><h2>${escapeHtml(className)}</h2><span>${students.length}명</span></header><div class="teacher-class-students">${students.map(student=>`<article class="teacher-student-row"><span class="avatar mint">${escapeHtml(student.display_name.slice(-2,-1)||"?")}</span><div><h3><span class="student-number">${escapeHtml(student.studentNumber||(student.numberCandidates.length>1?`${student.numberCandidates.join(" / ")} 중 확인 필요`:"엑셀 명단 없음"))}</span> ${escapeHtml(student.display_name)}</h3><p>${student.classNames.length?student.classNames.map(escapeHtml).sort(compareKorean).join(" · "):"엑셀 명단에 없어 분반 확인이 필요합니다"}</p></div><div><b>${student.points||0}P</b><small>${student.created_at?`${new Date(student.created_at).toLocaleDateString("ko-KR")} 가입`:""}</small>${!student.classNames.length?`<div class="student-class-assign"><select aria-label="${escapeHtml(student.display_name)} 분반 선택"><option value="">분반 선택</option>${classOptions}</select><button type="button" data-assign-student="${student.id}">배정</button></div>`:""}<button class="student-delete danger" type="button" data-delete-student="${student.id}">계정 삭제</button></div></article>`).join("")}</div></section>`).join("")||'<div class="empty-panel page-empty"><span>♙</span><h3>조건에 맞는 학생이 없습니다</h3></div>';
    host.querySelectorAll("[data-assign-student]").forEach(button=>button.onclick=async()=>{const select=button.previousElementSibling,classId=select.value;if(!classId){toast("배정할 분반을 선택해 주세요.");return}button.disabled=true;try{const {error}=await db.from("enrollments").insert({class_id:classId,student_id:button.dataset.assignStudent});if(error)throw error;await loadTeacherDirectory();toast("학생을 선택한 분반에 배정했습니다.")}catch(error){button.disabled=false;toast("분반 배정에 실패했습니다.");console.error(error)}})
    host.querySelectorAll("[data-delete-student]").forEach(button=>button.onclick=async()=>{const student=teacherStudents.find(item=>item.id===button.dataset.deleteStudent);if(!student||!confirm(`${student.studentNumber?`${student.studentNumber} `:""}${student.display_name} 학생의 로그인 계정과 분반 정보를 완전히 삭제할까요? 이 작업은 되돌릴 수 없습니다.`))return;button.disabled=true;try{const {data,error}=await db.rpc("delete_student_account",{target_student:student.id});if(error)throw error;if(!data)throw Error("계정을 삭제하지 못했습니다.");await loadTeacherDirectory();toast("학생 계정을 삭제했습니다.")}catch(error){button.disabled=false;toast(error.message||"계정 삭제에 실패했습니다.");console.error(error)}})
  }
  async function loadClasses(){
    if(remote.profile.role==='teacher'){
      const {data,error}=await db.from("classes").select("*").eq("teacher_id",remote.user.id).order("created_at");if(error)throw error;remote.classes=data;
    }else{
      const studentNumber=remote.user.user_metadata?.student_number;if(studentNumber){const {error}=await db.rpc("join_roster_class",{number:String(studentNumber)});if(error&&!/Could not find the function|does not exist/i.test(error.message))console.warn("명단 자동 분반 실패",error)}
      const code=sessionStorage.getItem("bio_pending_class_code")||remote.user.user_metadata?.class_code;if(code){const {error}=await db.rpc("join_class_with_code",{code});if(!error)sessionStorage.removeItem("bio_pending_class_code")}
      const {data,error}=await db.from("enrollments").select("class_id,classes(id,name)").eq("student_id",remote.user.id);if(error)throw error;remote.classes=data.map(x=>x.classes).filter(Boolean);
    }
    remote.selectedClass=remote.classes[0]?.id||null;renderClassControls();
  }
  function renderClassControls(){
    let bar=document.querySelector("#classControlBar");if(!bar){bar=document.createElement("div");bar.id="classControlBar";bar.className="class-control-bar";document.querySelector(".topbar").after(bar)}
    const options=remote.classes.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join("");
    bar.innerHTML=`<div class="wrap"><label>분반 <select id="classSelector">${options||'<option>등록된 분반 없음</option>'}</select></label>${remote.profile.role==='teacher'?'<button id="createClass">+ 분반 만들기</button>':''}<span>${remote.profile.role==='teacher'?'담당 분반의 과제와 제출물만 표시됩니다.':'가입한 분반의 자료와 과제만 표시됩니다.'}</span></div>`;
    const select=bar.querySelector("#classSelector");select.disabled=!remote.classes.length;select.onchange=async()=>{remote.selectedClass=select.value;await loadRemoteContent()};
    if(remote.profile.role==='teacher')bar.querySelector("#createClass").onclick=()=>classForm();
  }
  async function loadRemoteContent(){
    const [{data:m,error:me},{data:a,error:ae}]=await Promise.all([
      db.from("materials").select("*").order("created_at",{ascending:false}),
      remote.selectedClass?db.from("assignments").select("*").eq("class_id",remote.selectedClass).order("created_at",{ascending:false}):Promise.resolve({data:[],error:null})
    ]);if(me)throw me;if(ae)throw ae;
    materials.splice(0,materials.length,...m.map(x=>{const isLink=String(x.file_path||"").startsWith("url:");return{id:x.id,type:isLink?"link":x.kind,unit:isLink?"게임 · 앱 · 웹 활동":"모든 분반 공유",title:x.title,desc:x.description,pages:x.page_count,date:new Date(x.created_at).toLocaleDateString("ko-KR"),color:isLink?"blue":x.kind==='slide'?"green":"yellow",filePath:x.file_path,teacherId:x.teacher_id}}));
    let own=new Map();if(remote.profile.role==='student'){const {data:s}=await db.from("submissions").select("*").eq("student_id",remote.user.id);own=new Map((s||[]).map(x=>[x.assignment_id,x]))}
    assignments=a.map(x=>({id:x.id,title:x.title,desc:x.description,due:x.due_at?new Date(x.due_at).toLocaleString("ko-KR"):"마감 없음",dueAt:x.due_at,d:x.due_at?Math.max(0,Math.ceil((new Date(x.due_at)-Date.now())/86400000)):"-",done:own.has(x.id),submission:own.get(x.id)}));
    renderMaterials();renderHomeMaterials();remote.profile.role==='teacher'?renderTeacherAssignments():renderAssignments();addRoleActions();if(remote.profile.role==='teacher')await loadTeacherDirectory();await loadCommunity();
  }
  function renderHomeMaterials(){
    const card=document.querySelector(".today-card");if(!card)return;const heading=card.querySelector(".section-heading")?.outerHTML||"";
    card.innerHTML=heading+(materials.length?materials.slice(0,2).map((m,index)=>`<div class="lesson-row"><div class="lesson-number">${String(index+1).padStart(2,"0")}</div><div class="lesson-main"><div><span class="tag ${m.color}">${m.type==='slide'?'수업 슬라이드':m.type==='link'?'수업 활동 링크':'학습지'}</span><small>${escapeHtml(m.date)}</small></div><h3>${escapeHtml(m.title)}</h3><p>${escapeHtml(m.desc||"설명 없이 등록된 자료입니다.")}</p></div><button class="circle-arrow" data-open-material="${m.id}" aria-label="${escapeHtml(m.title)} 열기">${m.type==='link'?'↗':'→'}</button></div>`).join(""):'<div class="empty-panel"><span>▤</span><h3>등록된 수업 자료가 없습니다</h3><p>선생님이 자료를 올리면 이곳에 표시됩니다.</p></div>');
  }
  function decorateTeacherMaterials(){
    if(remote.profile?.role!=="teacher")return;
    document.querySelectorAll("#materialGrid [data-open-material]").forEach(open=>{const material=materials.find(x=>x.id===open.dataset.openMaterial);if(!material||material.teacherId!==remote.user.id)return;const actions=open.parentElement;if(!actions.querySelector("[data-edit-material]")){const edit=document.createElement("button");edit.type="button";edit.className="material-edit";edit.dataset.editMaterial=material.id;edit.textContent="수정";edit.onclick=event=>{event.stopPropagation();material.type==='link'?editActivityLinkForm(material):editMaterialForm(material)};open.before(edit)}if(!actions.querySelector("[data-delete-material]")){const remove=document.createElement("button");remove.type="button";remove.className="material-delete";remove.dataset.deleteMaterial=material.id;remove.textContent="삭제";remove.onclick=event=>{event.stopPropagation();deleteMaterial(material,remove)};open.before(remove)}});
  }
  async function deleteMaterial(material,button){
    if(!confirm(`'${material.title}' 자료를 삭제할까요? 학생들의 해당 자료 필기도 함께 삭제됩니다.`))return;
    button.disabled=true;button.textContent="삭제 중…";
    try{const {error}=await db.from("materials").delete().eq("id",material.id).eq("teacher_id",remote.user.id);if(error)throw error;if(material.filePath&&!material.filePath.startsWith("url:")){const {error:fileError}=await db.storage.from("class-materials").remove([material.filePath]);if(fileError)console.warn("자료 파일 정리 실패",fileError)}await loadRemoteContent();toast("수업 자료를 삭제했습니다.")}catch(error){button.disabled=false;button.textContent="삭제";toast("자료를 삭제하지 못했습니다.");console.error(error)}
  }
  function addRoleActions(){
    const materialHead=document.querySelector('[data-page="materials"] .page-head');if(remote.profile.role==='teacher'){let actions=materialHead.querySelector("#teacherMaterialActions");if(!actions){actions=document.createElement("div");actions.id="teacherMaterialActions";actions.className="teacher-material-actions";actions.innerHTML='<button id="teacherLinkButton" type="button">+ 활동 링크 올리기</button><button id="teacherMaterialButton" class="primary" type="button">+ 수업 자료 올리기</button>';const search=materialHead.querySelector(".search-box");if(search)actions.prepend(search);materialHead.append(actions);actions.querySelector("#teacherLinkButton").onclick=activityLinkForm;actions.querySelector("#teacherMaterialButton").onclick=materialForm}}
    const assignmentHead=document.querySelector('[data-page="assignments"] .page-head');let ab=assignmentHead.querySelector("#teacherAssignmentButton");if(remote.profile.role==='teacher'&&!ab){ab=document.createElement("button");ab.id="teacherAssignmentButton";ab.className="primary";ab.textContent="+ 과제 등록";ab.onclick=assignmentForm;assignmentHead.querySelector("#assignmentHelp")?.remove();assignmentHead.append(ab)}
  }
  function renderTeacherAssignments(){
    document.querySelector("#openCount").textContent=assignments.length;document.querySelector("#doneCount").textContent="-";
    document.querySelector("#assignmentList").innerHTML=assignments.map(a=>`<article class="assignment-item"><div class="assignment-date"><span>마감</span><strong>${a.d}</strong></div><div><span class="tag green">교사용</span><h3>${escapeHtml(a.title)}</h3><p>${escapeHtml(a.desc)}</p><small>${a.due} 마감</small></div><div class="assignment-actions"><button data-view-submissions="${a.id}">제출 현황</button><button data-edit-assignment="${a.id}">수정</button><button class="danger" data-delete-assignment="${a.id}">삭제</button></div></article>`).join("")||'<div class="empty-panel page-empty"><span>✓</span><h3>이 분반에 등록된 과제가 없습니다</h3></div>';
    document.querySelectorAll("[data-view-submissions]").forEach(b=>b.onclick=()=>viewSubmissions(b.dataset.viewSubmissions));
    document.querySelectorAll("[data-edit-assignment]").forEach(b=>b.onclick=()=>editAssignmentForm(assignments.find(item=>item.id===b.dataset.editAssignment)));
    document.querySelectorAll("[data-delete-assignment]").forEach(b=>b.onclick=()=>deleteAssignment(assignments.find(item=>item.id===b.dataset.deleteAssignment),b));
  }
  assignmentAction=async id=>{const item=assignments.find(x=>String(x.id)===String(id));if(!item)return;if(item.done){toast("이미 제출한 과제입니다.");return}submissionForm(item)};
  function modalForm(title,html,onSubmit){let modal=document.querySelector("#backendModal");if(!modal){modal=document.createElement("div");modal.id="backendModal";modal.className="modal hidden";document.body.append(modal)}modal.innerHTML=`<form class="modal-card form-card"><button class="modal-close" type="button">×</button><h2>${escapeHtml(title)}</h2>${html}<p class="form-error"></p><button class="primary wide" type="submit">저장하기</button></form>`;modal.classList.remove("hidden");document.body.style.overflow="hidden";modal.querySelector(".modal-close").onclick=()=>{modal.classList.add("hidden");document.body.style.overflow=""};modal.querySelector("form").onsubmit=async e=>{e.preventDefault();const error=modal.querySelector(".form-error");try{await onSubmit(new FormData(e.target));modal.classList.add("hidden");document.body.style.overflow="";await loadClasses();await loadRemoteContent();toast("저장했습니다.")}catch(x){error.textContent=x.message}}}
  function classForm(){modalForm("새 분반 만들기",'<label>분반 이름<input name="name" required placeholder="예: 2학년 3반"></label><label>학생 가입 코드<input name="code" required minlength="6" placeholder="6자리 이상"></label>',async fd=>{const {error}=await db.from("classes").insert({name:fd.get("name"),join_code:String(fd.get("code")).toUpperCase(),teacher_id:remote.user.id});if(error)throw error})}
  function assignmentForm(){if(!remote.selectedClass){toast("먼저 분반을 만들어 주세요.");return}modalForm("과제 등록",'<label>과제명<input name="title" required></label><label>설명<textarea name="description"></textarea></label><label>제출 기한<input name="due" type="datetime-local" required></label>',async fd=>{const {error}=await db.from("assignments").insert({class_id:remote.selectedClass,teacher_id:remote.user.id,title:String(fd.get("title")).trim(),description:String(fd.get("description")||"").trim(),due_at:new Date(fd.get("due")).toISOString()});if(error)throw error})}
  function localDateTimeValue(value){if(!value)return"";const date=new Date(value),offset=date.getTimezoneOffset()*60000;return new Date(date-offset).toISOString().slice(0,16)}
  function editAssignmentForm(item){if(!item)return;modalForm("과제 수정",`<label>과제명<input name="title" required value="${escapeHtml(item.title)}"></label><label>설명<textarea name="description">${escapeHtml(item.desc||"")}</textarea></label><label>제출 기한<input name="due" type="datetime-local" required value="${localDateTimeValue(item.dueAt)}"></label>`,async fd=>{const {error}=await db.from("assignments").update({title:String(fd.get("title")).trim(),description:String(fd.get("description")||"").trim(),due_at:new Date(fd.get("due")).toISOString()}).eq("id",item.id).eq("teacher_id",remote.user.id);if(error)throw error})}
  async function deleteAssignment(item,button){if(!item||!confirm(`'${item.title}' 과제를 삭제할까요? 학생 제출물도 함께 삭제됩니다.`))return;button.disabled=true;try{const {data:files}=await db.from("submissions").select("file_path").eq("assignment_id",item.id),{error}=await db.from("assignments").delete().eq("id",item.id).eq("teacher_id",remote.user.id);if(error)throw error;const paths=(files||[]).map(row=>row.file_path).filter(Boolean);if(paths.length)await db.storage.from("assignment-submissions").remove(paths);await loadRemoteContent();toast("과제를 삭제했습니다.")}catch(error){button.disabled=false;toast("과제를 삭제하지 못했습니다.");console.error(error)}}
  let pptxModulePromise=null;
  function loadPptxModule(){return pptxModulePromise??=import("./vendor/pptx-renderer/pptx-renderer.browser.es.js")}
  async function inspectMaterialFile(file){if(!(file instanceof File)||!file.size)throw Error("올릴 PDF, PPTX 또는 이미지 파일을 선택해 주세요.");if(/\.ppt$/i.test(file.name))throw Error("구형 PPT 파일은 바로 표시할 수 없습니다. PowerPoint에서 PPTX로 다시 저장한 뒤 올려 주세요.");let pageCount=1;if(/\.pdf$/i.test(file.name)||file.type==='application/pdf'){if(!window.pdfjsLib)throw Error("PDF 기능을 불러오지 못했습니다. 페이지를 새로고침한 뒤 다시 시도해 주세요.");const pdf=await window.pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;pageCount=pdf.numPages;await pdf.destroy()}else if(/\.pptx$/i.test(file.name)||file.type==='application/vnd.openxmlformats-officedocument.presentationml.presentation'){const {parseZip,buildPresentation,RECOMMENDED_ZIP_LIMITS}=await loadPptxModule();const presentation=buildPresentation(await parseZip(await file.arrayBuffer(),RECOMMENDED_ZIP_LIMITS),{lazySlides:true});pageCount=presentation.slides.length;if(!pageCount)throw Error("PPTX 안에서 표시할 슬라이드를 찾지 못했습니다.")}else if(!/^image\/(png|jpeg|webp)$/i.test(file.type))throw Error("PDF, PPTX, PNG, JPG, WEBP 파일만 올릴 수 있습니다.");return pageCount}
  async function uploadMaterialFile(file){const pageCount=await inspectMaterialFile(file),safe=`${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`,path=`shared/${remote.user.id}/${safe}`;const {error}=await db.storage.from("class-materials").upload(path,file,{contentType:file.type||undefined});if(error)throw error;return{path,pageCount}}
  const materialFileField='<label>PDF, PPTX 또는 이미지<input name="file" type="file" accept=".pdf,.pptx,application/pdf,application/vnd.openxmlformats-officedocument.presentationml.presentation,image/png,image/jpeg,image/webp"></label>';
  const requiredMaterialFileField=materialFileField.replace('name="file"','name="file" required');
  function materialForm(){modalForm("전체 공유 수업 자료 올리기",`<p class="shared-notice">PDF와 PPTX는 슬라이드별로 자동 표시됩니다. 구형 PPT 파일은 PowerPoint에서 PPTX로 저장한 뒤 올려 주세요.</p><label>자료 종류<select name="kind"><option value="slide">수업 슬라이드</option><option value="worksheet">학습지</option></select></label><label>제목<input name="title" required></label><label>설명<textarea name="description"></textarea></label>${requiredMaterialFileField}`,async fd=>{const file=fd.get("file"),uploaded=await uploadMaterialFile(file);const {error}=await db.from("materials").insert({class_id:null,teacher_id:remote.user.id,kind:fd.get("kind"),title:String(fd.get("title")).trim(),description:String(fd.get("description")||"").trim(),file_path:uploaded.path,page_count:uploaded.pageCount});if(error){await db.storage.from("class-materials").remove([uploaded.path]);throw error}})}
  function editMaterialForm(material){modalForm("수업 자료 수정",`<p class="shared-notice">제목과 설명만 수정하려면 새 파일을 선택하지 않아도 됩니다.</p><label>자료 종류<select name="kind"><option value="slide" ${material.type==='slide'?'selected':''}>수업 슬라이드</option><option value="worksheet" ${material.type==='worksheet'?'selected':''}>학습지</option></select></label><label>제목<input name="title" required value="${escapeHtml(material.title)}"></label><label>설명<textarea name="description">${escapeHtml(material.desc)}</textarea></label>${materialFileField}<small>새 파일을 선택하면 현재 슬라이드 파일이 교체됩니다.</small>`,async fd=>{const file=fd.get("file"),replacement=file instanceof File&&file.size?await uploadMaterialFile(file):null,changes={kind:fd.get("kind"),title:String(fd.get("title")).trim(),description:String(fd.get("description")||"").trim()};if(replacement){changes.file_path=replacement.path;changes.page_count=replacement.pageCount}const {error}=await db.from("materials").update(changes).eq("id",material.id).eq("teacher_id",remote.user.id);if(error){if(replacement)await db.storage.from("class-materials").remove([replacement.path]);throw error}if(replacement&&material.filePath){const {error:fileError}=await db.storage.from("class-materials").remove([material.filePath]);if(fileError)console.warn("이전 자료 파일 정리 실패",fileError)}})}
  function normalizeActivityUrl(value){let url;try{url=new URL(String(value).trim())}catch{throw Error("https://로 시작하는 올바른 활동 링크를 입력해 주세요.")}if(!['http:','https:'].includes(url.protocol))throw Error("http 또는 https 링크만 등록할 수 있습니다.");return url.href}
  const activityLinkFields=(material=null)=>`<p class="shared-notice">Wordwall, Kahoot, Quizizz, Google Forms 등 수업에서 사용할 게임·앱 주소를 등록할 수 있습니다.</p><label>활동 이름<input name="title" required value="${escapeHtml(material?.title||"")}" placeholder="예: 세포 구조 복습 게임"></label><label>설명<textarea name="description" placeholder="학생에게 보여 줄 간단한 안내">${escapeHtml(material?.desc||"")}</textarea></label><label>활동 링크<input name="url" type="url" required value="${escapeHtml(material?.filePath?.slice(4)||"")}" placeholder="https://..."></label>`;
  function activityLinkForm(){modalForm("수업 활동 링크 올리기",activityLinkFields(),async fd=>{const {error}=await db.from("materials").insert({class_id:null,teacher_id:remote.user.id,kind:"slide",title:String(fd.get("title")).trim(),description:String(fd.get("description")||"").trim(),file_path:`url:${normalizeActivityUrl(fd.get("url"))}`,page_count:1});if(error)throw error})}
  function editActivityLinkForm(material){modalForm("수업 활동 링크 수정",activityLinkFields(material),async fd=>{const {error}=await db.from("materials").update({title:String(fd.get("title")).trim(),description:String(fd.get("description")||"").trim(),file_path:`url:${normalizeActivityUrl(fd.get("url"))}`}).eq("id",material.id).eq("teacher_id",remote.user.id);if(error)throw error})}
  function submissionForm(item){modalForm(item.title,'<label>제출 내용<textarea name="body"></textarea></label><label>파일 첨부<input name="file" type="file"></label>',async fd=>{const file=fd.get("file");let path=null;if(file&&file.size){path=`${item.id}/${remote.user.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const {error}=await db.storage.from("assignment-submissions").upload(path,file);if(error)throw error}const body=String(fd.get("body")).trim();if(!body&&!path)throw Error("내용을 입력하거나 파일을 첨부해 주세요.");const {error}=await db.from("submissions").upsert({assignment_id:item.id,student_id:remote.user.id,body,file_path:path},{onConflict:"assignment_id,student_id"});if(error)throw error})}
  async function viewSubmissions(id){const {data,error}=await db.from("submissions").select("*,profiles!submissions_student_id_fkey(display_name)").eq("assignment_id",id).order("submitted_at");if(error)throw error;modalForm("제출 현황",`<div class="submission-list">${data.length?data.map(s=>`<article><b>${escapeHtml(s.profiles?.display_name||"학생")}</b><small>${new Date(s.submitted_at).toLocaleString("ko-KR")}</small><p>${escapeHtml(s.body||"첨부 파일 제출")}</p>${s.file_path?`<button type="button" data-download-submission="${s.file_path}">파일 열기</button>`:""}</article>`).join(""):'<div class="empty-panel">아직 제출한 학생이 없습니다.</div>'}</div>`,async()=>{});document.querySelector("#backendModal button[type=submit]").remove();document.querySelectorAll("[data-download-submission]").forEach(b=>b.onclick=async()=>{const {data}=await db.storage.from("assignment-submissions").createSignedUrl(b.dataset.downloadSubmission,60);if(data)window.open(data.signedUrl,"_blank")})}
  let remoteDocument=null,documentLoadId=0;
  if(window.pdfjsLib)window.pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";
  const appOpenViewer=openViewer,appGoSlide=goSlide;
  openViewer=async function(id){
    const material=materials.find(x=>x.id===id);if(material?.type==='link'){const url=normalizeActivityUrl(material.filePath.slice(4));window.open(url,"_blank","noopener,noreferrer");return}const loadId=++documentLoadId;remoteDocument?.viewer?.destroy();remoteDocument=null;document.querySelector("#documentCanvas")?.remove();document.querySelector("#pptxCanvas")?.remove();appOpenViewer(id);if(!material?.filePath)return;
    document.querySelector("#saveStatus").textContent="원본 자료 불러오는 중…";
    const {data,error}=await db.storage.from("class-materials").createSignedUrl(material.filePath,3600);if(error){toast("자료를 불러오지 못했습니다.");return}
    try{
      if(/\.pdf$/i.test(material.filePath)){if(!window.pdfjsLib)throw Error("PDF.js unavailable");const response=await fetch(data.signedUrl);if(!response.ok)throw Error(`파일 응답 오류 (${response.status})`);const pdf=await window.pdfjsLib.getDocument({data:await response.arrayBuffer()}).promise;if(loadId!==documentLoadId){await pdf.destroy();return}remoteDocument={type:"pdf",pdf};material.pages=pdf.numPages}
      else if(/\.pptx$/i.test(material.filePath)){const response=await fetch(data.signedUrl);if(!response.ok)throw Error(`파일 응답 오류 (${response.status})`);const {PptxViewer,RECOMMENDED_ZIP_LIMITS}=await loadPptxModule();if(loadId!==documentLoadId)return;const host=document.querySelector("#lessonCanvas"),pptxHost=document.createElement("div");pptxHost.id="pptxCanvas";host.insertBefore(pptxHost,document.querySelector("#slideContent"));const viewer=await PptxViewer.open(await response.arrayBuffer(),pptxHost,{renderMode:"slide",fitMode:"contain",zipLimits:RECOMMENDED_ZIP_LIMITS,lazySlides:true,pdfjs:false});if(loadId!==documentLoadId){viewer.destroy();return}remoteDocument={type:"pptx",viewer};material.pages=viewer.slideCount;host.style.aspectRatio=`${viewer.slideWidth}/${viewer.slideHeight}`}
      else if(/\.ppt$/i.test(material.filePath))throw Error("구형 PPT 형식은 PPTX로 다시 저장해야 합니다.");
      else remoteDocument={type:"image",url:data.signedUrl};
      if(loadId!==documentLoadId)return;
      document.querySelector("#slideTotal").textContent=material.pages;document.querySelector("#slideThumbs").innerHTML=Array.from({length:material.pages},(_,i)=>`<div class="slide-thumb" data-slide="${i}"><b>${i+1}</b><br>원본 ${i+1}쪽</div>`).join("");document.querySelectorAll("[data-slide]").forEach(t=>t.onclick=()=>goSlide(+t.dataset.slide));await renderOriginalPage();
    }catch(error){console.error(error);document.querySelector("#saveStatus").textContent="자료 열기 실패";toast("PDF 또는 이미지 파일을 열 수 없습니다. 다시 업로드해 주세요.")}
  };
  goSlide=function(index){appGoSlide(index);if(remoteDocument)renderOriginalPage()};
  async function renderOriginalPage(){
    if(!remoteDocument||!state.currentMaterial)return;const host=document.querySelector("#lessonCanvas"),content=document.querySelector("#slideContent");content.innerHTML="";content.className="slide-content original-document";
    if(remoteDocument.type==='pptx')await remoteDocument.viewer.renderSlide(state.currentSlide);
    else{let base=document.querySelector("#documentCanvas");if(!base){base=document.createElement("canvas");base.id="documentCanvas";host.insertBefore(base,content)}if(remoteDocument.type==='pdf'){const page=await remoteDocument.pdf.getPage(state.currentSlide+1),viewport=page.getViewport({scale:1.6});base.width=viewport.width;base.height=viewport.height;host.style.aspectRatio=`${viewport.width}/${viewport.height}`;await page.render({canvasContext:base.getContext("2d"),viewport}).promise}else await new Promise((resolve,reject)=>{const img=new Image;img.crossOrigin="anonymous";img.onload=()=>{base.width=img.naturalWidth;base.height=img.naturalHeight;host.style.aspectRatio=`${img.naturalWidth}/${img.naturalHeight}`;base.getContext("2d").drawImage(img,0,0);resolve()};img.onerror=reject;img.src=remoteDocument.url})}
    document.querySelectorAll(".slide-thumb").forEach((x,n)=>x.classList.toggle("active",n===state.currentSlide));document.querySelector("#prevSlide").disabled=state.currentSlide===0;document.querySelector("#nextSlide").disabled=state.currentSlide===state.currentMaterial.pages-1;resizeCanvas();await loadDrawing();document.querySelector("#saveStatus").textContent="✓ 개인 필기 불러옴";
  }
  async function loadCommunity(){
    const [{data:q,error:qe},{data:ans,error:ane},{data:posts,error:pe},{data:people,error:pre},{data:postLikes,error:likeError}]=await Promise.all([
      db.from("questions").select("*").order("created_at",{ascending:false}),db.from("answers").select("*").order("created_at"),db.from("lounge_posts").select("*").order("created_at",{ascending:false}),db.from("profiles").select("id,display_name"),db.from("lounge_likes").select("post_id,user_id")
    ]);if(qe||ane||pe||pre||likeError){console.error(qe||ane||pe||pre||likeError);return}const names=new Map((people||[]).map(p=>[p.id,p.display_name])),likesByPost=new Map();for(const like of postLikes||[]){const values=likesByPost.get(like.post_id)||[];values.push(like.user_id);likesByPost.set(like.post_id,values)}
    const allPaths=[...(q||[]),...(ans||[]),...(posts||[])].flatMap(item=>item.image_paths||[]),signedByPath=new Map();
    await Promise.all(allPaths.map(async path=>{const {data}=await db.storage.from("community-images").createSignedUrl(path,3600);if(data?.signedUrl)signedByPath.set(path,data.signedUrl)}));
    const imageUrls=item=>(item.image_paths||[]).map(path=>signedByPath.get(path)).filter(Boolean),unitLabels={unit1:"1단원",unit2:"2단원",unit3:"3단원"};
    questions=(q||[]).map(item=>({id:item.id,title:escapeHtml(item.title),body:escapeHtml(item.body),rawTitle:item.title,rawBody:item.body,author:escapeHtml(names.get(item.author_id)||"학생"),authorId:item.author_id,canEdit:item.author_id===remote.user.id,status:(ans||[]).some(a=>a.question_id===item.id)?"answered":"waiting",category:item.category||"unit1",subject:unitLabels[item.category]||"1단원",imagePaths:item.image_paths||[],imageUrls:imageUrls(item),likes:0,answers:(ans||[]).filter(a=>a.question_id===item.id).map(a=>({id:a.id,author:escapeHtml(names.get(a.author_id)||"학생"),authorId:a.author_id,canEdit:a.author_id===remote.user.id,text:escapeHtml(a.body),rawText:a.body,imagePaths:a.image_paths||[],imageUrls:imageUrls(a),helpful:a.helpful_count||0}))}));
    lounge=(posts||[]).map(item=>{const postLikeUsers=likesByPost.get(item.id)||[];return{id:item.id,type:item.category,label:{activity:"내 활동 자랑",article:"기사·자료",debate:"토론",wonder:"신기한 생물"}[item.category]||"라운지",title:escapeHtml(item.title),body:escapeHtml(item.body),rawTitle:item.title,rawBody:item.body,author:escapeHtml(names.get(item.author_id)||"학생"),authorId:item.author_id,canEdit:item.author_id===remote.user.id,canLike:item.author_id!==remote.user.id,likedByMe:postLikeUsers.includes(remote.user.id),imagePaths:item.image_paths||[],imageUrls:imageUrls(item),likes:postLikeUsers.length,comments:0,link:item.link}});renderQuestions();renderLounge();
  }
  async function uploadCommunityImages(fd,kind){
    const files=fd.getAll("images").filter(file=>file instanceof File&&file.size);
    if(files.length>5)throw Error("사진은 한 번에 최대 5장까지 올릴 수 있습니다.");
    for(const file of files){if(!/^image\/(jpeg|png|webp|gif)$/i.test(file.type))throw Error("JPG, PNG, WEBP, GIF 사진만 올릴 수 있습니다.");if(file.size>10*1024*1024)throw Error("사진 한 장의 크기는 10MB 이하여야 합니다.")}
    const paths=[];
    try{for(const file of files){const extension=(file.name.split(".").pop()||"jpg").replace(/[^a-z0-9]/gi,"").toLowerCase(),path=`${remote.user.id}/${kind}/${Date.now()}-${crypto.randomUUID()}.${extension}`;const {error}=await db.storage.from("community-images").upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;paths.push(path)}return paths}
    catch(error){if(paths.length)await db.storage.from("community-images").remove(paths);throw error}
  }
  async function appendedImagePaths(fd,kind,existing=[]){const added=await uploadCommunityImages(fd,kind);if(existing.length+added.length>5){if(added.length)await db.storage.from("community-images").remove(added);throw Error("기존 사진을 포함해 최대 5장까지만 저장할 수 있습니다.")}return[...existing,...added]}
  window.bioEditQuestion=id=>{const item=questions.find(question=>String(question.id)===String(id));if(!item?.canEdit)return;modalForm("질문 수정",`<label>단원 분류<select name="category"><option value="unit1" ${item.category==='unit1'?'selected':''}>1단원</option><option value="unit2" ${item.category==='unit2'?'selected':''}>2단원</option><option value="unit3" ${item.category==='unit3'?'selected':''}>3단원</option></select></label><label>질문 제목<input name="title" required value="${escapeHtml(item.rawTitle)}"></label><label>자세한 내용<textarea name="body" required>${escapeHtml(item.rawBody)}</textarea></label><label>사진 추가 (선택)<input name="images" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple></label><small>기존 사진은 유지되며 전체 사진은 최대 5장입니다. 질문은 수정만 가능하고 삭제할 수 없습니다.</small>`,async fd=>{const paths=await appendedImagePaths(fd,"questions",item.imagePaths),{error}=await db.from("questions").update({category:fd.get("category"),title:String(fd.get("title")).trim(),body:String(fd.get("body")).trim(),image_paths:paths}).eq("id",item.id).eq("author_id",remote.user.id);if(error)throw error})};
  window.bioEditLounge=id=>{const item=lounge.find(post=>String(post.id)===String(id));if(!item?.canEdit)return;modalForm("라운지 글 수정",`<label>종류<select name="type"><option value="activity" ${item.type==='activity'?'selected':''}>내 활동 자랑</option><option value="article" ${item.type==='article'?'selected':''}>기사·자료</option><option value="debate" ${item.type==='debate'?'selected':''}>토론</option><option value="wonder" ${item.type==='wonder'?'selected':''}>신기한 생물</option></select></label><label>제목<input name="title" required value="${escapeHtml(item.rawTitle)}"></label><label>내용<textarea name="body" required>${escapeHtml(item.rawBody)}</textarea></label><label>참고 링크<input name="link" type="url" value="${escapeHtml(item.link||"")}"></label><label>사진 추가 (선택)<input name="images" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple></label><small>기존 사진은 유지되며 글은 수정만 가능하고 삭제할 수 없습니다.</small>`,async fd=>{const paths=await appendedImagePaths(fd,"lounge",item.imagePaths),{error}=await db.from("lounge_posts").update({category:fd.get("type"),title:String(fd.get("title")).trim(),body:String(fd.get("body")).trim(),link:fd.get("link")||null,image_paths:paths}).eq("id",item.id).eq("author_id",remote.user.id);if(error)throw error})};
  window.bioLikeLounge=async id=>{try{const {data,error}=await db.rpc('like_lounge_post',{target_post:id});if(error)throw error;await loadCommunity();toast(data?.liked?'좋아요를 보냈어요. 글 작성자에게 5P가 지급됐습니다!':'이미 좋아요를 누른 글입니다.')}catch(error){toast(error.message||'좋아요 처리에 실패했습니다.')}};
  window.bioEditAnswer=id=>{const item=questions.flatMap(question=>question.answers).find(answer=>String(answer.id)===String(id));if(!item?.canEdit)return;modalForm("답변 수정",`<label>답변 내용<textarea name="body" required>${escapeHtml(item.rawText)}</textarea></label><label>사진 추가 (선택)<input name="images" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple></label><small>기존 사진은 유지되며 답변은 수정만 가능하고 삭제할 수 없습니다.</small>`,async fd=>{const paths=await appendedImagePaths(fd,"answers",item.imagePaths),{error}=await db.from("answers").update({body:String(fd.get("body")).trim(),image_paths:paths}).eq("id",item.id).eq("author_id",remote.user.id);if(error)throw error})};
  const localDynamicSubmit=document.querySelector("#dynamicForm").onsubmit;
  document.querySelector("#dynamicForm").onsubmit=async event=>{
    const mode=state.formMode?.mode;if(!remote.user||!['question','lounge','answer'].includes(mode)){return localDynamicSubmit.call(event.currentTarget,event)}event.preventDefault();const fd=new FormData(event.currentTarget),errorBox=document.querySelector("#formError");try{
      if(mode==='question'){const imagePaths=await uploadCommunityImages(fd,"questions"),{error}=await db.from("questions").insert({class_id:null,author_id:remote.user.id,category:fd.get("category"),title:fd.get("title"),body:fd.get("body"),image_paths:imagePaths});if(error){if(imagePaths.length)await db.storage.from("community-images").remove(imagePaths);throw error}}
      if(mode==='lounge'){const imagePaths=await uploadCommunityImages(fd,"lounge"),{error}=await db.from("lounge_posts").insert({author_id:remote.user.id,category:fd.get("type"),title:fd.get("title"),body:fd.get("body"),link:fd.get("link")||null,image_paths:imagePaths});if(error){if(imagePaths.length)await db.storage.from("community-images").remove(imagePaths);throw error}}
      if(mode==='answer'){const imagePaths=await uploadCommunityImages(fd,"answers"),{error}=await db.from("answers").insert({question_id:state.formMode.data.id,author_id:remote.user.id,body:fd.get("body"),image_paths:imagePaths});if(error){if(imagePaths.length)await db.storage.from("community-images").remove(imagePaths);throw error}}
      closeModals();await loadCommunity();if(mode==='lounge'){await syncPointsAndCelebrate();toast("라운지에 글을 올리고 10P를 받았어요!")}else toast("모든 분반에 공유되었습니다.");
    }catch(error){errorBox.textContent=error.message}
  };
  const localSave=saveDrawing;saveDrawing=function(){localSave();if(!remote.user||remote.profile?.role!=="student"||!state.currentMaterial)return;db.from("personal_notes").upsert({material_id:state.currentMaterial.id,student_id:remote.user.id,page_number:state.currentSlide+1,drawing_data:canvas.toDataURL(),memo:document.querySelector("#sideNote").value},{onConflict:"material_id,student_id,page_number"}).then(({error})=>{if(error)console.error(error)})};
  const localLoad=loadDrawing;loadDrawing=async function(){localLoad();if(!remote.user||remote.profile?.role!=="student"||!state.currentMaterial)return;const {data}=await db.from("personal_notes").select("drawing_data,memo").eq("material_id",state.currentMaterial.id).eq("student_id",remote.user.id).eq("page_number",state.currentSlide+1).maybeSingle();if(data?.drawing_data){const img=new Image;img.onload=()=>ctx.drawImage(img,0,0,canvas.clientWidth,canvas.clientHeight);img.src=data.drawing_data}if(data)document.querySelector("#sideNote").value=data.memo||""};
  function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
  db.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'&&session)setTimeout(openPasswordRecovery,0)});window.addEventListener('focus',()=>{if(remote.user)syncPointsAndCelebrate()});
  db.auth.getSession().then(({data})=>{if(data.session)activate(data.session).catch(e=>{console.error(e);toast("계정 정보를 불러오지 못했습니다.")})});
})();
